name: 'notion_analytics'
config-version: 2

# Vars must be at the SAME level as 'name' and 'config-version'
vars:
  dbt_utils:
    surrogate_key_treat_nulls_as_empty_strings: True

profile: 'notion_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  notion_analytics:
    # Set the default materialization for all models to be a View
    +materialized: view

    # Exclude the example models that came with the project
    example:
      +enabled: false